### ISSUE TITLE
Build failed "Swift Language Version"

### ISSUE THREAD

**Issue by nertilzhuri** [prscX/react-native-material-showcase-ios#3]
First of all, thank you for this library, it looks awesome.

I followed installation and linking as described in your README, but unfortunately I was not able to build the project because of a dependencies error ("Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift."). I am attaching the screenshot of the error:

![screenshot at dec 15 23-05-37](https://user-images.githubusercontent.com/12595516/34062436-cfed3e56-e1ec-11e7-8a11-5346b28b1d0e.png)

I would be grateful if you could help. Thank you.

"react": "16.0.0",
"react-native": "0.51.0",

By the way, the Manual Installation url is pointing to a 404 url.

**Comment by prscX** [comment]
Thanks @nertilzhuri for reporting the issue

Are you using CocoaPods in your main project? Based on my knowledge we normally encounter this issue when Swift Language Version is not defined

I have verified in RNMaterialShowcase & MaterialShowcase project and Swift version specified:

<img width="946" alt="screen shot 2017-12-16 at 12 37 10 pm" src="https://user-images.githubusercontent.com/28862892/34068282-289472ce-e25e-11e7-8f4a-c2d3c023c847.png">
<img width="964" alt="screen shot 2017-12-16 at 12 37 23 pm" src="https://user-images.githubusercontent.com/28862892/34068284-2d368d58-e25e-11e7-96ea-137d0e612d1f.png">

When I compile the Example project it is building successfully. Can you please verify the below configuration in your main project:

<img width="1004" alt="screen shot 2017-12-16 at 12 37 34 pm" src="https://user-images.githubusercontent.com/28862892/34068295-560532c0-e25e-11e7-9972-29128da5573d.png">
<img width="1004" alt="screen shot 2017-12-16 at 12 37 54 pm" src="https://user-images.githubusercontent.com/28862892/34068296-5748f7de-e25e-11e7-9f26-8baeec27f293.png">

Please let me know in case it does not works

Thanks
Pranav

**Comment by nertilzhuri** [comment]
Hello Pranav,

Thank you for your response. The problem apparently is that MaterialShowcase requires Swift 4, for which I have not updated Xcode yet due to some legacy projects.

<img width="753" alt="screenshot at dec 18 16-50-08" src="https://user-images.githubusercontent.com/12595516/34114855-2d512ba6-e414-11e7-927c-5664f4713828.png">

I will try again soon once I update the Xcode and post if I have problems (which I doubt). Thank you for your time and library.
