### ISSUE TITLE
Tint Color Problem

### ISSUE THREAD

**Issue by YusufBesim** [prscX/react-native-material-showcase-ios#8]
Hello,

I wanted to change tint color (blue one)
I tried many way to change but not working.
Any idea how can i change tint color?

let appTourTarget = AppTourView.for(thiz.button1, {
            primaryText: 'This is a target button 1',
            secondaryText: 'We have the best targets, believe me',
            primaryTextColor: '#FFF',
            secondaryTextColor: '#FFF',
            backgroundPromptColor:"#99000000",
            targetTintColor:"#FFF", // Not working
            targetHolderColor:"#999"
        });

**Comment by prscX** [comment]
Thanks @YusufBesim for raising the issue. 

I will have a look and will update you soon on the same. Meantime few you have spare time can you please verify whether targetTintColor is passed to native bridge and native material-showcase-ios library or not.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @YusufBesim, I have fixed the `tintColor` issue, basically the native library based taking tint color  directly from target view and not from setters. 

I have released a new version `0.0.4`, can you please download the latest version and verify it once. Please let me know in case you still face the same issue.

Thanks
Pranav
